// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt_SklepButow.Models;

#nullable disable

namespace ProjektSklepButow.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Projekt_SklepButow.Models.PostProdukcjaButow_Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cena")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kolor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rodzaj")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PostProdukcjaButow_Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cena = 345,
                            Kolor = 0,
                            Marka = "Adidas",
                            Model = "Gazeli",
                            Rodzaj = 0
                        },
                        new
                        {
                            Id = 2,
                            Cena = 597,
                            Kolor = 1,
                            Marka = "New Balance",
                            Model = "574",
                            Rodzaj = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
